README.md
app-auth-sample/README.md

Updated the readme for the links.

This is to update ReadMe

---

graphql-sample/callbackFilter.graphql
graphql-sample/realTimeQueuedTasks.graphql

realtime example and callback example

---

README.md
app-auth-sample/README.md
call-recording-download-sample/README.md
graphql-sample/README.md
postman-sample/README.md

updating readme

---

configuration-app-sample/README.md
configuration-app-sample/copy.env
configuration-app-sample/index.js
configuration-app-sample/src/public/index.html
configuration-app-sample/src/public/js/app.js
configuration-app-sample/src/public/js/authURL.js
configuration-app-sample/src/public/js/helpers/buildForm.js
configuration-app-sample/src/public/js/helpers/fetchApi.js
configuration-app-sample/src/public/js/helpers/fixFormError.js
configuration-app-sample/src/public/js/helpers/formError.js
configuration-app-sample/src/public/js/helpers/getBearerToken.js
configuration-app-sample/src/public/js/sa-lib/select.js

config app updates

---

app-auth-sample/README.md

readme vidcast

---

token-app-sample/README.md

readme updates & video

---

call-recording-download-sample/package-lock.json
call-recording-download-sample/package.json

Fixing the package.json dependencies

added missing dependacies from package.json

---

callback-sample/README.md
callback-sample/frontEndForm.js
callback-sample/package-lock.json
callback-sample/package.json
callback-sample/server.js

Callback sample

---

callback-sample/README.md

Read me updates

---

call-recording-download-sample/README.md

updating readme with the Webhook sample

readme update

---

widget-sample-101/README.md

fix grammer

---

postman-sample/README.md

new postman collection

---

iframe-widget-sample/Analayzer_iFrame_Widget_Layout.json
iframe-widget-sample/README.md

Analyzer iFrame widget - Sample

analyzer-iframe-widget

---

app-auth-sample/server.js
graphql-sample/advanced.graphql
graphql-sample/basicFields.graphql
graphql-sample/callbackFilter.graphql
graphql-sample/globalVariables.graphql
graphql-sample/interactionDetails.graphql
graphql-sample/lastAgentInteraction.graphql
graphql-sample/realTimeQueuedTasks.graphql
graphql-sample/simple.graphql
graphql-sample/totalCallsByAni.graphql
graphql-sample/wallboard-query-samples/callCountByEntryPoint.graphql
graphql-sample/wallboard-query-samples/callCountByTeam.graphql
graphql-sample/wallboard-query-samples/callStatsByAgent.graphql
graphql-sample/wallboard-query-samples/callStatsByQueue.graphql
graphql-sample/wallboard-query-samples/totalAgentSessionsRealTime.graphql
graphql-sample/wallboard-query-samples/totalCallsRealTime.graphql
graphql-sample/wallboard-query-samples/totalCallsRealTimeConnected.graphql
graphql-sample/wallboard-query-samples/totalCallsRealTimeQueued.graphql
graphql-wallboard-sample/controller/wallboard/totalAgentSessionsRealTime.js

Graphql fields to and from mandatory

---

desktop-api-sample/README.md
desktop-api-sample/WebexCC Desktop APIs - Sample.postman_collection.json

A look at all the new desktop REST APIs

Desktop REST APIs - early preview

---

desktop-api-sample/views/src/0_webSocket/getSocketURL.js

Agent kept going to idle, this was because we were setting keepalive to true but not sending 'keeplive' every 15 secs.
changed it to false.

fixed idle state issue

---

token-service-sample/LICENSE
token-service-sample/firestore.rules
token-service-sample/index.js
token-service-sample/package.json
token-service-sample/readme.md

adding token-server-sample

---

README.md
app-auth-sample/README.md
call-recording-samples/call-recording-download-sample/README.md
call-recording-samples/call-recording-extractor-sample/README.md
callback-sample/README.md
configuration-samples/configuration-app-sample/README.md
configuration-samples/configuration-extraction-sample/README.md
customer-journey-samples/UC1-directing-customer-input/README.md
customer-journey-samples/UC2-tracking-the-repeat-caller/README.md
customer-journey-samples/cjds-postman-example/README.md
customer-journey-samples/manage-identities-and-aliases/README.md
desktop-sample/desktop-api-sample/README.md
dialogflow-sample/README.md
dialogflow-sample/inline-editor.js
dialogflow-sample/package.json
ewt-sample/README.md
postman-sample/README.md
preferred-agent-callback/README.md
reporting-samples/graphql-powerbi-sample/README.md
reporting-samples/graphql-sample/README.md
reporting-samples/graphql-wallboard-sample/README.md
token-app-sample/README.md
widget-samples/addressbook-widget-sample/README.md
widget-samples/audio-widget-sample/README.md
widget-samples/desktop-js-sdk-callcontrol-sample/README.md
widget-samples/desktop-js-sdk-sample/README.md
widget-samples/giftcard-sample/README.md
widget-samples/iframe-widget-sample/README.md
widget-samples/widget-sample-101/README.md

`Dialog Flow Example`
`Fulfillment service example`
`dialogflow-sample and Support Links for all the samples`

dialogflow-example

---

widget-samples/addressbook-widget-sample/README.md
widget-samples/desktop-js-sdk-sample/README.md

fixed broken links

---

widget-samples/desktop-js-sdk-callcontrol-sample/README.md
widget-samples/desktop-js-sdk-callcontrol-sample/src/widget-SDK-Voice.js

call-control SDK widget

---

widget-samples/giftcard-sample/src/components/sa-gift-card.js

Widget Samples

---

webex-instant-connect-sample/README.md

`Webex Instant Connect with Webex Contact Center`
`Voice to Video Escalation for Webex Contact Center`
`Images, Postman collection, Readme, Sample API Calls`

Instant connect for WebexCC

---

widget-samples/send-email-sample/README.md
widget-samples/send-email-sample/src/components/sa-digital-email.js

send-email-sample

---

widget-samples/send-sms-sample/README.md
widget-samples/send-sms-sample/src/components/sa-digital-sms.js

send-sms-sample

---

webex-instant-connect-sample/README.md

Added links in readme

---

postman-sample/New WebexCC OAuth2 APIs - v2.postman_collection.json

postman changes

---

postman-sample/New WebexCC OAuth2 APIs - v2.postman_collection.json

postman change env

---

.gitignore
call-recording-samples/call-recording-extractor-sample/README.md
call-recording-samples/call-recording-extractor-sample/src/main/java/com/webexcc/api/model/AgentActivity.java
call-recording-samples/call-recording-extractor-sample/src/main/java/com/webexcc/api/model/Capture.java
call-recording-samples/call-recording-extractor-sample/src/main/java/com/webexcc/api/model/Transcription.java

Added missing attributes for Captures API

---

customer-journey-use-cases/CJDS 10 Use Cases.postman_collection01.json

CJDS Use Cases

---

token-management-samples/token-service-sample/index.js

updated typo with send in preflight check
By submitting this pull request, I confirm that my contribution is made under the terms of the [CONTRIBUTING.md](CONTRIBUTING.md) …

Update index.js typo in preflight

---

call-recording-samples/call-recording-download-sample/GCPCallRecordingDownload.js

GCP recording upload sample

---

callback-samples/README.md
callback-samples/callback-sample-java-login/README.md
callback-samples/callback-sample-nodejs-login/README.md

Jiwyatt readme update

---

reporting-samples/graphql-sample/DataDictionary/AAR.md
reporting-samples/graphql-sample/DataDictionary/ASR.md
reporting-samples/graphql-sample/DataDictionary/CAR.md
reporting-samples/graphql-sample/DataDictionary/CLR.md
reporting-samples/graphql-sample/DataDictionary/CSR.md

Updated Descriptions for each data type

---

widget-samples/rss-header-widget-sample/build/rss-widget.js
widget-samples/rss-header-widget-sample/layout.json
widget-samples/rss-header-widget-sample/src/rss-widget.js

Fixing issues with LitElement attributes

---

call-recording-samples/call-recording-extractor-sample/src/main/java/com/webexcc/api/captures/controller/WebRestController.java
call-recording-samples/call-recording-extractor-sample/src/main/java/com/webexcc/api/captures/service/ApiService.java
call-recording-samples/call-recording-extractor-sample/src/main/java/com/webexcc/api/captures/util/SetEnv.java
call-recording-samples/call-recording-extractor-sample/src/main/java/com/webexcc/api/model/CaptureAttributes.java
call-recording-samples/call-recording-extractor-sample/src/main/resources/application.properties
reporting-samples/graphql-powerbi-sample/graphql/advanced.graphql
reporting-samples/graphql-powerbi-sample/graphql/allContactFields.graphql
reporting-samples/graphql-powerbi-sample/graphql/basicFields.graphql
reporting-samples/graphql-powerbi-sample/graphql/callCountByEntryPoint.graphql
reporting-samples/graphql-powerbi-sample/graphql/callbackFilter.graphql
reporting-samples/graphql-powerbi-sample/graphql/globalVariableFilter.graphql
reporting-samples/graphql-powerbi-sample/graphql/globalVariables.graphql
reporting-samples/graphql-powerbi-sample/graphql/interactionDetails.graphql
reporting-samples/graphql-powerbi-sample/graphql/lastAgentInteraction.graphql
reporting-samples/graphql-powerbi-sample/graphql/realTimeQueuedTasks.graphql
reporting-samples/graphql-powerbi-sample/graphql/simple.graphql
reporting-samples/graphql-powerbi-sample/graphql/tasks.graphql
reporting-samples/graphql-powerbi-sample/graphql/totalAgentSessionsRealTime.graphql
reporting-samples/graphql-powerbi-sample/graphql/totalCallsByAni.graphql
reporting-samples/graphql-powerbi-sample/graphql/totalCallsRealTime.graphql
reporting-samples/graphql-powerbi-sample/graphql/totalCallsRealTimeConnected.graphql
reporting-samples/graphql-powerbi-sample/graphql/totalCallsRealTimeQueued.graphql
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/controller/WebRestController.java
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/service/SearchGraphQLService.java
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/util/MyEnv.java
reporting-samples/graphql-powerbi-sample/src/main/resources/application.properties

added pagination to graphQL files & request limiter & Java memory logger

---

webex-instant-connect-sample/voice-to-video/README.md
webex-instant-connect-sample/voice-to-video/VoiceFlow_InstantConnect.json

fixed flow and readme

---

reporting-samples/graphql-sample/DataDictionary/CLR.md
reporting-samples/graphql-sample/README.md

Update documentation for Search API

---

address-book-sample/README.md
address-book-sample/wxccAddressBookSample.py

initial commit

---

reporting-samples/graphql-powerbi-sample/README.md
reporting-samples/graphql-powerbi-sample/graphql/agentSession.graphql
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/controller/WebRestController.java
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/model/AgentSession.java
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/model/AgentSessions.java
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/model/ChannelInfo.java
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/model/Data.java
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/service/SearchGraphQLService.java
reporting-samples/graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/util/ExportUtil.java

Added
updated task search
agentSession search
agentSession was an new search request feature.
graphql-powerbi-sample/graphql/agentSession.graphql
graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/controller/WebRestController.java
graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/model/AgentSession.java
graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/model/AgentSessions.java
graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/model/ChannelInfo.java
graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/model/Data.java
graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/service/SearchGraphQLService.java
graphql-powerbi-sample/src/main/java/com/webexcc/api/demo/util/ExportUtil.java
NA
- [ x] I have tested my changes thoroughly and they work as …

Added agentSession search support

---

customer-journey-samples/cjds-postman-example/JDS CiscoLive.postman_collection.json

Updated JDS Postman collection

updated collection

---

customer-journey-samples/cjds-postman-example/JDS CiscoLive.postman_collection.json

Fixed AUTH section for OAuth vars

---

reporting-samples/graphql-sample/README.md

Documented the Filter Limit in search API doc

Document Filter Limit

---

WEbEx-AI-Template-API/template_APIs.postman_collection.json

This update includes the Postman collection for Webex AI use case templates. The collection provides a set of preconfigured API calls designed to help developers quickly test and integrate various Webex AI functionalities.
To streamline development and testing workflows by offering a standardized set of use case templates. This collection aims to improve accessibility, reduce onboarding time, and enhance collaboration among team members working on Webex AI integrations.
Added a new Postman collection file: template_APIs.postman_collection.json
Verified collection functionality against current Webex AI endpoint

WebEX AI Template API
